# Generated by Django 5.1.1 on 2024-10-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_program', '0001_initial'),
        ('user', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='training_programs',
            field=models.ManyToManyField(blank=True, to='training_program.trainingprogram'),
        ),
    ]
